add_newline = true
command_timeout = 200
format = "$directory$character"

[character]
error_symbol = "[❯](bold red)"
success_symbol = "[❯](bold cyan)"

[directory]
truncation_length = 1
truncation_symbol = ""
format = "[$path]($style) "
style = "bold cyan"
